### PR TITLE
Remove assignment to read-only property in view

### PR DESCRIPTION
**Pull request by mertcetin**
"rendered" property is inherited from Component and it does not
have a setter implemented. It's default value is already false so
An explicit assignment here is unnecessary.

### CODE REVIEW

**Comment by dashersw** [comment]
@mertcetin then we can also remove the constructor?

**Comment by mertcetin** [comment]
Yes but I assumed you would like to keep it together with its really descriptive comment.

**Comment by dashersw** [comment]
Maybe we could move it to the class documentation a few lines up? Idk.

**Comment by mertcetin** [comment]
Let me try and see how it looks.

**Pull request merged**
